spring:
  application:
    name: fs-spark-service
  profiles:
    active: dev,idev
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.iisquare.fs.spark.web.dsconfig.NamingStrategy
