server:
  port: 7811

fs:
  spark:
    k8sUrl: https://192.168.2.77:6443
    kvConfigUrl: # json file path for key value config
    plugins:
      dir: ./spark/web/plugins
      url: # plugins path for class loader
