fs:
  format:
    date: yyyy-MM-dd HH:mm:ss

rpc:
  member:
    name: fs-member-service
    rest: http://127.0.0.1:7801
  analyse:
    name: fs-analyse-service
    rest: http://127.0.0.1:7802
  flink:
    name: fs-flink-service
    rest: http://127.0.0.1:7803
  xlab:
    name: fs-xlab-service
    rest: http://127.0.0.1:7805
  spider:
    name: fs-spider-service
    rest: http://127.0.0.1:7806
  admin:
    name: fs-admin-service
    rest: http://127.0.0.1:7808

feign:
  hystrix:
    enabled: true # Enable Fallback
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 5000
      fs-flink-service:
        connectTimeout: 1000
        readTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 5000

spring:
  http:
    encoding:
      charset: UTF-8
  thymeleaf:
    mode: LEGACYHTML5
    suffix: .html
    cache: false
  datasource:
    primary:
      url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8&useSSL=false
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8&useSSL=false
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    member:
      table-prefix: fs_member_
      url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8&useSSL=false
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8&useSSL=false
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    spider:
      table-prefix: fs_spider_
      url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8&useSSL=false
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8&useSSL=false
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    flink:
      table-prefix: fs_flink_
      url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8&useSSL=false
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs-project?characterEncoding=utf-8&useSSL=false
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
